config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :reviews, only: [ :new, :create ]
  end
  resources :users, only: [ :show ]

  resources :orders_to_products, only: [:create, :update, :destroy]
  resources :orders, only: [ :show, :update ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :status, presence: true
  has_many :orders_to_products, dependent: :destroy
end

app/models/orders_to_product.rb
class OrdersToProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, :unit_price, presence: true
end

app/models/orders_to_products.rb
class OrdersToProducts < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, :unit_price, presence: true

end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch::Model


  belongs_to :user

  has_many :orders, through: :ordersToProduct
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :stock, presence: true, numericality: { only_integer: true }

  has_one_attached :photo


  # multisearchable against: [:title, :syllabus]

  # pg_search_scope :search_by_name_and_description,
  #   against: [:name, :description],
  #   using: {
  #     tsearch: { prefix: true }
  #   }

  pg_search_scope :global_search,
      against: [:name, :description],
      associated_against: {
        user: [:name, :username, :address]
      },
      using: {
        tsearch: { prefix: true }
      }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :description, length: { maximum: 200 }
  validates :rating, presence: true, acceptance: { accept: (1..5) }
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :username, :password, :address, :cellphone, presence: true
  validates :username, :cellphone, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  # we will let the geocode access our address and convert it to latitude and longitude.
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :orders, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password, :password_confirmation, :photo, :name, :cellphone, :address, :seller])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password, :password_confirmation, :photo, :name, :username, :cellphone, :address, :seller])
  end

  # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end
    private

      def skip_pundit?
        devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
      end
    end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @user = current_user
    @order = Order.find(params[:id])
    if @order.status == 'open'
      @myproducts = OrdersToProduct.where(order_id:@order.id)
    end
    authorize @user
  end

  def update
    @user = current_user
    @order = Order.find(params[:id])
    authorize @order
    redirect_to user_path(current_user) if @order.update(order_params)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

# @ordersofuser = Order.where(user_id:@user.id)
# @ordersopen = []

# @ordersofuser.each do |order|
#   @ordersopen << order if order.status == 'open'

app/controllers/orders_to_products_controller.rb
class OrdersToProductsController < ApplicationController
  def create
    open_order = current_user.orders.find_by(status: "open")
    open_order ||= current_user.orders.create(status: "open")

    @orders_to_product = OrdersToProduct.new(orders_to_product_params)
    @orders_to_product.unit_price = @orders_to_product.product.price
    @orders_to_product.order = open_order
    authorize @orders_to_product
    @orders_to_product.save

    # flash[:notice] = "Successfully added to cart. #{view_context.link_to 'wanna see your cart?', order_path(@orders_to_product.order_id)}".html_safe
    # redirect_to @orders_to_product.product

    redirect_to @orders_to_product.product, notice: "Succesfully added to cart"
  end

  def update
  end

  def destroy
    @product_in_order = OrdersToProduct.find(params[:id])
    @product_in_order.destroy
    redirect_to order_path(@product_in_order.order_id)
    authorize @product_in_order
  end

  private

  def orders_to_product_params
    params.require(:orders_to_product).permit(:quantity, :product_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all

    if params[:query].present?
      @products = Product.global_search(params[:query])
    else
      @products = Product.all
    end

    @products.each do |product|
      @productreviews = Review.where(product_id: product.id)
      @sum = 0
      @number = 0
      @productreview = 0
      unless @productreviews.empty?
        @productreviews.each do |review|
          @sum += review.rating
          @number += 1
        end
        @productreview = @sum / @number
      end
      product.review = @productreview
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = policy_scope(Product)
  end

  def show
    @user = User.find(@product.user_id)
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    authorize @product
    if @product.save!
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @product.update(product_params)
    # redirect_to
  end

  def destroy
    @product.destroy product_path(@product)
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:name, :description, :stock, :price, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
    authorize @review
  end

 def create
    @review = Review.new(review_params)
    @product = Product.find(params[:product_id])
    @review.product = @product
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:description, :rating)
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def show
    authorize @user
    @orders = Order.where(user_id: @user.id)
    @products = Product.where(user_id: @user.id)
    @purchased_orders = @orders.each { |order| order.status == "bought"}

    @markers = [{
      lat: @user.latitude,
      lng: @user.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { user: @user }),
      image_url: helpers.asset_url('logo.png')
    }]
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>

  </body>
</html>

app/views/orders/show.html.erb
<div class="form-centralize-review">
  <div class="heading-rounded-sm">
    <h2> My Cart</h2>
  </div>
  <div class="form-borders-cart">

    <% if @myproducts %>

      <table class="table">
        <thead >
          <tr class="table-title">
            <th scope="col col-pro layout-inline" >Product</th>
            <th scope="qty qty-plus>Quantity</th>
            <th scope="col col-price col-numeric">Unit Price</th>
            <th scope="col col-vat col-numeric">Partial</th>
          </tr>

        </thead>
          <tbody>
            <% sum = 0  %>
            <% @myproducts.each do |product| %>
              <tr>
                <th scope='row'><%= Product.find(product.product_id).name %></th>
                <td>$ <%=  product.quantity  %></td>
                <td>$ <%=  product.unit_price %></td>
                <td> <% sum += (product.quantity) * (product.unit_price) %> $ <%=  (product.quantity) * (product.unit_price) %> <%= link_to orders_to_product_path(product),
                method: 'DELETE' , remote:true do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
      <hr>
      <p><strong>To pay : $ <%= sum %></strong></p>

    <%= link_to 'Pay', order_path(@order, order: { status: 'bought' }), method: 'PATCH', class: 'btn btn-primary' %>
    <%=  redirect_to user_path(current_user) unless @order.status = 'open' %>
  <% end %>
  </div>
</div>

app/views/orders_to_product/show.html.erb
<%= link_to "go back to products", products_path %>
<h2>Name: <%= @product.name%></h2>
<p>Price: <%= @product.price  %></p>


<%# link to seller's profile %>
<% @product.review.each do |review| %>
  <% sum_of_ratings += review.rating %>
<% end %>
<% if @product.review.count == 0 %>
  <p> This product has not been reviewed <p>
<% else %>
  <p>Average Rating: <%= "#{sum_of_ratings/@product.review.count} Reviews made: #{@product.review.count}" %></p>
<% end %>

app/views/orders_to_products/show.html.erb
<%= link_to "go back to products", products_path %>

<div>
  <h2>Name: <%= @product.name%></h2>
  <p>Price: <%= @product.price  %></p>
</div>
<%# link to seller's profile %>


<%# List the products in cart %>
<% @product = 0 %>
<% product.each do |item| %>
  <%= @product += item%>
<% end %>
<%# End of listed products  %>



<p> Resume of the orders</p>
 <p></p>

app/views/pages/edit.html.erb
<div class="fixing-margin">
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name  %>
    <%= f.input :decription %>
    <%= f.input :price %>
    <%= f.input :stock %>
    <%= f.sumbit %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
  <h1>Local Market</h1>
  <p>
    <span id="banner-typed-text"></span>
  </p>
</div>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group" id='search-bar'>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Buy from Us, Find a product"
  %>
  <%#= submit_tag "Search", class: "btn btn-primary" %>
  <button name="button" type="submit" class="btn btn-flat">
    <i class="fas fa-search"></i> Search
  </button>

  </div>
<% end %>


<div class="fixing-the-card">
  <div class="cards">
    <% if @products %>
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
          <div class="card-trip">


            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, class: 'card-trip-img' if product.photo.attached? %>
            <% else %>
              <%= image_tag "logo.png", height: 160, width: 240, crop: :fill, class: 'empty card-trip-img' %>

            <% end %>

            <div class="card-trip-infos">
              <div>

                <h2 class="product-name"><%= product.name.capitalize%></h2>
                <% white_stars = 5 - product.review.round %>
                <p>
                  <% product.review.round.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% white_stars.times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                <!-- <p><%= product.description %> </p> -->


                <!-- <p><%= product.user_id %> </p> -->
              </div>
              <h2 class="card-trip-pricing"> $ <%= product.price %></h2>

              <%= cl_image_tag product.user.photo.key, class: 'card-trip-user avatar-bordered'if product.user.photo.attached? %>
              <%= image_tag "avatar-default-copy.png", crop: :fill, class: "avatar dropdown-toggle avatar-bordered", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false unless product.user.photo.attached?%>
            </div>
          </div>

        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/new.html.erb
<div class="fixing-margin">
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name  %>
    <%= f.input :decription %>
    <%= f.input :price %>
    <%= f.input :stock %>
    <%= f.sumbit %>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="fixing-margin">
  <div class="form-centralize">
    <h2>Editing your product</h2>
    <div class="form-borders">
      <%= simple_form_for @product do |f| %>
        <div class="input-color">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :stock %>
          <%= f.input :price, hint: 'in dollars'%>

          <%= f.input :photo, as: :file, hint: 'pick a good picture to display your product' %>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h2>Products</h2>
<% @products.each do |product| %>
  <p><%= link_to "#{product.name}", product_path(product) %></p>
  <p><%= product.price %></p>
<% end %>

app/views/products/new.html.erb
<div class="form-centralize">
  <div class="form-borders">
    <h2>Selling a new Product</h2>
    <%= simple_form_for @product do |f| %>
      <div class="input-color">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :stock %>
        <%= f.input :price, hint: 'in dollars'%>

        <%= f.input :photo, as: :file, hint: 'pick a good picture to display your product' %>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="product-show-container col-12 pt-100" style="background-color: white">

  <div class="product-details d-flex col-12">
    <div class="product-img col-5">
      <%= cl_image_tag @product.photo.key, class: "product-image rounded-lg", crop: :fill if @product.photo.attached? %></div>
    <div class="product-info col-7">
      <%# link to seller's profile %>
      <p> Seller: <%= link_to "#{@user.name}", user_path(@user), class: "seller-link" %> </p>
      <h1 class="product-name"><%= @product.name%></h1>
      <% if policy(@user).update? %>
        <%= link_to edit_product_path(@product) do%>
          <i class="fas fa-edit"></i>
        <% end %>
      <% end %>

      <%# rating average logic %>

      <% sum_of_ratings = 0 %>
      <% @product.reviews.each do |review| %>
        <% sum_of_ratings += review.rating %>
      <% end %>
      <% if @product.reviews.count == 0 %>
        <p> This product has not been reviewed <p>
      <% else %>
        <% rating = sum_of_ratings/@product.reviews.count %>
        <% white_stars = 5 - rating %>
        <p>
          <% rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% white_stars.times do %>
            <i class="far fa-star"></i>
          <% end %>
          <%= "(#{@product.reviews.count})" %>
        </p>
      <% end %>
      <%# rating average logic end %>
      <p>Price: $<%= @product.price  %></p>
      <%#Stock logic%>
      <% if @product.stock == 0 %>
        <p> sold out <p>
      <% else %>
        <p>Stock: <%= @product.stock %></p>
      <% end %>
      <%# stock logic end%>
      <% # Add to cart logic and form %>
      <%= simple_form_for OrdersToProduct.new do |f| %>
        <%= f.input :product_id, as: :hidden, input_html: {value: @product.id} %>
        <%= f.input :quantity, collection: (1..10), include_blank: false, class: "quantity-button" %>
        <%= f.submit "Add to cart", class: "add-cart-button" %>
      <% end %>
      <%# description %>
      <h3>Description:</h3>
      <p><%= @product.description %></p>

    </div>
  </div>



  <div class="reviews-container d-flex col-12">
    <div class="review-rating col-3">
      <%# rating average logic %>
<!--       <% if @product.reviews.count == 0 %>
        <p> This product has not been reviewed <p>
      <% else %>
        <p>
          <% rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% white_stars.times do %>
            <i class="far fa-star"></i>
          <% end %>
          <%= "(#{@product.reviews.count})" %>
        </p>
      <% end %> -->
      <%# rating average logic end %>
    </div>
    <div class="reviews-list col-9">
      <div class="reviews-title col-12"> <h2>Reviews:</h2> </div>
      <%# New Review %>
      <%= link_to "New Review", new_product_review_path(@product.id), class: "review-new" %>
         <% @product.reviews.each do |review| %>
              <% if review.description != "" %>
      <div class="card mb-4">
        <div class="card-header">
          <% review.rating.times do %>
             <i class="fas fa-star"></i>
          <% end %>
          <% empty_stars = 5 - review.rating %>
          <% empty_stars.times do %>
             <i class="far fa-star"></i>
          <% end %>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p><%= " #{review.description} #{review.rating}" %></p>
            <footer class="blockquote-footer"><%= "#{review.created_at} " %><cite title="Source Title">Source Title</cite></footer>
          </blockquote>
        </div>
      </div>
        <% end %>
            <% end %>

app/views/reviews/new.html.erb
<div class="form-centralize-review">
  <div class="form-borders">
    <h2>Add a Review</h2>
    <%= simple_form_for [ @product, @review ] do |f| %>
      <%= f.input :description %>
      <%= f.input :rating, collection: (1..5) %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link text-secondary" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached?%>
          <%= image_tag "avatar-default-copy.png", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false unless current_user.photo.attached?%>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <% if current_user.orders.last%>
              <%= link_to order_path(current_user.orders.last), class: "dropdown-item"  do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/users/_info_window.html.erb
<h2><%= user.name %></h2>
<p><%= user.address  %></p>

app/views/users/show.html.erb
<div class="user-container col-12" style="background-color: white">



    <% if current_user == @user %>
     <div class="user-details col-12 d-flex align-items-center">
        <div class="profile-avatar col-3 style=" text-align: center;"">

          <%= cl_image_tag current_user.photo.key, crop: :fill, class: "profile-pic", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached?%>
          <%= image_tag "avatar-default-copy.png", crop: :fill, class: "profile-pic", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false unless current_user.photo.attached?%>
          <div><h3><%= @user.name.capitalize %></h3></div>
        </div>
        <div class="user-info col-3">
          <%= link_to edit_user_registration_path, class: "nav-link" do %>
            <i class="fas fa-user-edit"></i>
          <% end %>
          <% if @user.seller %>
            <h3>My Seller Profile</h3>
          <% end %>
          <p>Username: <%= @user.username %></p>
          <p> Email: <%= @user.email %></p>
          <p> Address: <%= @user.address %></p>
          <p> Cellphone: <%= @user.cellphone %></p>

        </div>
        <div class="user-map col-6">
          <div id="map"
          style="width: 100%; height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
      <% if current_user.seller %>
        <div class="user-properties col-12 d-flex">
          <div class="seller-recent-orders col-5">
            <div class="card">
              <div class="card-header">
                My Previous Purchases
              </div>
              <div class="card-body">

                <% if current_user.orders != 0%>
                  <% @purchased_orders.each do |purchased|%>
                      <% counter = 1%>
                      <div class="d-flex"><%= "Order #{counter} Purchased: #{purchased.updated_at}" %> <%= link_to "review purchase", order_path(purchased), class: "btn btn-light" %></div>

                      <% counter += 1%>
                  <% end %>
                <% else %>
                    <div> <h3>No previous orders</h3>  </div>
                <% end %>

              </div>
            </div>
          </div>
          <div class="user-products col-7">
           <div class="card mb-4">
              <h5 class="card-header d-flex" style="justify-content: space-between;"> <div>My Products </div> <div> <%= link_to "+ create", new_product_path, class: "btn btn-light" %></div></h5>
              <div class="card-body">
                <% current_user.products.each do |product|%>
                  <div class="products-cards col-12 d-flex mb-3">
                    <div class="product-card-photo col-4">
                      <%= cl_image_tag product.photo.key, class: "product-image-user-show", crop: :fill if product.photo.attached? %>
                    </div>
                  <div class="product-card-information-edit col-8">
                    <p><%= product.name %></p>
                    <div class="d-flex">
                      <%= link_to "Go to Product", product_path(product), class: "btn btn-light mr-2"%>

                      <%= link_to "Edit Product", edit_product_path(product), class: "btn btn-light"%>
                    </div>

                  </div>
                  </div>
                <% end %>
              </div>

            </div>
          </div>
        </div>
      <% end %>

    <% end %>

    <% if current_user != @user %>
    <div class="user-details col-12 d-flex align-items-center">
        <div class="profile-avatar col-3" style=" text-align: center;">

          <%= cl_image_tag @user.photo.key, crop: :fill, class: "profile-pic", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached?%>
          <%= image_tag "avatar-default-copy.png", crop: :fill, class: "profile-pic", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false unless current_user.photo.attached?%>
          <div><h3><%= @user.name.capitalize %></h3></div>
        </div>
        <div class="user-info col-3">
          <% if @user.seller %>
            <h3>Seller's Profile</h3>
          <% end %>
          <p> Address: <%= @user.address %></p>
          <p> Cellphone: <%= @user.cellphone %></p>

        </div>
        <div class="user-map col-6">
          <div id="map"
          style="width: 100%; height: 100%;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
    </div>

      <div class="user-properties col-12 d-flex">

          <div class="user-products col-8">
           <div class="card mb-4">
              <h5 class="card-header d-flex" style="justify-content: space-between;"> <div>Other Products by this Seller </div></h5>
              <div class="card-body">
                <% @user.products.each do |product|%>
                  <div class="products-cards col-12 d-flex mb-3">
                    <div class="product-card-photo col-3">
                      <%= cl_image_tag product.photo.key, class: "product-image-user-show" if product.photo.attached? %>
                    </div>
                  <div class="product-card-information-edit col-9">
                    <h3><%= product.name %></h3>
                    <%= link_to "Go to Product", product_path(product), class: "btn btn-light"%>
                  </div>
                  </div>
                <% end %>
              </div>

            </div>
          </div>
        </div>

    <% end %>

</div>